### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by KommareddyMonicaTejaswi** [INFO-526-S24/project-final-RoboCops#3]
The following is the peer review of the project proposal by [VizMasters]. The team members that participated in this review are 

- [Kondapaneni Siva Rohit ] - @[Sivarohitk]
- [Rohit Vatsava Kalakala] - @[Rohit-Vatsava]
- [Miki Katyal] - @[MIKIKATYAL]
- [Ajay Kumar] - @[AjaykATgithub]
- [Surya Vardhan Dama] - @[suryavardhandama]
- [Monica Tejaswi Kommareddy] - @[KommareddyMonicaTejaswi]
- ...

- Describe the goal of the project.
This project analyses the fatal police shootings in the U.S., their factors, and whether there are any reasons behind them.

- Describe the data used or collected.
They have used 8 different datasets which are sourced from Kaggle repositories. The data is wrangled well for the project. It contains data about fatality rates, City Census Datasets, City Population Data, State Population Data.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
For question 1 part a) using PercentagePeopleBelowPovertyLevel.csv  to see how the severity of police use of force and the level of poverty in communities are connected which is represented using barplot's/columnplots, part b) to check for any correlation between socioeconomic status, particularly income & educational levels, and incidents of police killings using regression analysis and half eye plots.
For question 2 part a) using leaflet or ggmap plots alongside column plots to visualize ratio of Police Shootings to Population over time. part b)using heatmaps and stacked bar plots to visualize the impact of different instruments relavant to Shooting Intensity across racial groups and age distributions

- Is there anything that is unclear from the proposal?
The proposal provides a clear overview of the project objectives, datasets used, and analysis approaches. However, more details on specific analysis methods and potential biases in the data could enhance clarity.

- Provide constructive feedback on how the team might be able to improve their project.
Consider ethical considerations associated with the analysis of sensitive topics.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are interested in how economic factors and racial demographics correlate with the police use of forces. This gonna help us look into the ongoing discussions of systemic inequalities and excessive use of police forces to control the situations arising due to these factors.

- Provide constructive feedback on any issues with file and/or code organization.
We didn't find any issues with the code or file organization they have done a good job of organizing the file/code in a good way

- (Optional) Any further comments or feedback?
There were no further comments just it would be good to include all the references at the end of the proposal.

**Comment by sachinpatil3115** [comment]
Thank you for your feedback,

We have noted your points for improvement and have made the necessary improvements accordingly.

Feedback 1: Detail on specific analysis methods.
Action taken: We have already defined an analysis approach to explore the data, which includes correlation analysis to identify patterns and relationships between different variables, and visualization methods to address the questions.

Feedback 2: Show correlation between economic factors, racial demographics, and police use of force.
Action taken: We have integrated the analysis concerning socioeconomic status and racial demographics in police shootings.

Feedback 3: References not included at the end of the proposal.
Action taken: We have compiled and included a comprehensive list of references in the final proposal.

Thanks,
Team RoboCop
