### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by ayeshakhatunsujana** [INFO-526-S24/project-final-RoboCops#5]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

- Ayesha Khatun - @ayeshakhatunsujana
- Kaarthik Sai Patibandla - @zeuszapper
- Shreemithra Naveen - @shreemithran
- Eeshaan Sourabh Reddy Mummila - @EeshaanReddy
- Anusha Nagaraja - @anusharaj1997
- Amaan Mohammed Yunus Salim Mulla- @amaanam
---

#### 1. Purpose of Code
- [x] Clearly defined and understood
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [x] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [x] Code documentation (e.g., comments) is sufficient
- [ ] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments
- code structure  can be more organized. for example you can add new line after a comma (line 91, 266 in index.qmd file)
- There is a good deal of code duplication, particularly in the areas that plot 2015 and 2016. Consider writing a function to handle the charting to cut down on redundancy and improve the maintainability of the code rather than replicating the same plotting code every year.
- Although there are many areas in the code where more comments may increase clarity, particularly in the sophisticated data processing or charting processes, the code is generally well-commented.
- References can be added.
- The procedure of creating the animation is handled nicely, however make sure the GIF animation format is the best fit for the specified use case. Other formats, such as MP4 or HTML5, can be more suited depending on the situation.
- It would be beneficial to include a little more detail on the changes being made in commit messages. 

---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by ArunKoundinya** [comment]
Hi All,

Fixes Provided:
1) Created prepare_label_data function to avoid duplicate data frames.
2) Create prepare_alaska_map_data function to easily customer annotate the alaska map into usa map.
3) plot_shooting_intensity function created to ensure for easy replication of plots for multiple years state wise.
4) plot_shooting_intensity_city function created to ensure for easy replication of plots for multiple years city wise.

Thnx,
Arun Koundinya

**Comment by ArunKoundinya** [comment]
Issues fixed in the code commits
